### ISSUE TITLE
No Consent Options for Provided Patient Picker App 

### ISSUE THREAD

**Issue by sdan22** [dancinnamon-okta/okta-smartfhir-docs#10]
I followed the reference implementation and when the provided patient picker app pops up I am not getting the consent selection. As shown on the image (launch_example.png) in the README.md.

I think this may be why my request is being denied with a 401 unauthorized even though my claims and scopes are correct. 

Any ideas why the consent selection would not be popping up?

**Comment by dancinnamon-okta** [comment]
Hey-
Can you tell if your browser is attempting to go to the /patient_authorization URL?  If it is- then I'm thinking perhaps it's failing to invoke the proper Okta APIs.  That sample custom consent screen takes the scopes requested, and it calls the Okta APIs to get the friendly names and descriptions, and also it retrieves the client app icon.  So you might verify your API_KEY and OKTA_ORG variables to make sure they're correct.

**Comment by sdan22** [comment]
Hi!

I found the issue I did not set block services to yes for the scopes.

thanks!

**Comment by dancinnamon-okta** [comment]
Ahh right!  Glad you got it figured out!

**Comment by sdan22** [comment]
@dancinnamon-okta Thank you for the support and for this reference implementation!
