### ISSUE TITLE
Patient picker API in the logs getting an error because of double https://https://

### ISSUE THREAD

**Issue by feroze-shahpurwala-visiontree** [dancinnamon-okta/okta-smartfhir-docs#12]
<img width="1221" alt="Screenshot 2022-12-29 at 10 11 57 AM" src="https://user-images.githubusercontent.com/118219830/209992754-92ba5c9b-dae8-4e82-9a72-b1e08e6ebe44.png">

When I try to access the Fhir API  it successfully bring up the login page and once I am logged in successfully it redirects to a white screen with the following error: " Unable to retrieve requested scope definitions and client info from the authorization server." 

I looked at the logs for the patient picker API and I noticed something strange. The request is failing because of a double https://https:// as seen in the picture. Why does this double protocol only happen in this part and what could I possible change to get it to work correctly?

**Comment by feroze-shahpurwala-visiontree** [comment]
Ah it was due to the `OKTA_ORG` setting you are not supposed to include the protocol in the url, once I fixed it, this issue no longer existed. 

`OKTA_ORG:  dev-XXXXXXXX.okta.com`

that is the format of `OKTA_ORG`

**Comment by dancinnamon-okta** [comment]
I'm back- I'm glad you figured out the issue! I am working on a new version of my deployment and code that will standardize on the naming of variables a little better to hopefully eliminate some of this confusion.
