### ISSUE TITLE
 Error: The authorization code is invalid or has expired.

### ISSUE THREAD

**Issue by feroze-shahpurwala-visiontree** [dancinnamon-okta/okta-smartfhir-docs#13]
So far I have worked through the issues and I have postman as the client getting an access token from okta and the login page comes up, I can login with my user account and then the patient picker UI appears and I am able to select a patient and after i select a patient and click button to approve the UI disappears and it then routes back to postman and should have the access token but instead I get this error in the console:

` Error: The authorization code is invalid or has expired.`

And the last request before the error was calling the token endpoint. So for some reason I am not getting a valid authorization code

**Comment by dancinnamon-okta** [comment]
One thing you might check is your Okta logs to see if there's any errors there.  My guess right now is that your authorization request is not matching an authorization server access policy within Okta. These policies are there to allow you on the server side to allow certain clients to request certain scopes, allow them to use different oauth2 grants, and they also control token lifetimes.

**Comment by feroze-shahpurwala-visiontree** [comment]
```
config: {
    url: 'https://dev-XXXXXXXX.okta.com/oauth2/default/v1/token',
    method: 'post',
    data: 'client_id=XXXXXXXXXXXXX&client_secret=XXXXXXXXXXXX&grant_type=authorization_code&**redirect_uri=https://abcdefghi.execute-api.us-west-2.amazonaws.com/dev/smart_proxy_callback&code=undefined',**
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': 'axios/0.21.2',
      'Content-Length': 223
    }
```

this is part of the logs from the token smart proxy and check out the redirect uri there you see how the code=undefined. I wonder how is that happening?

**Comment by feroze-shahpurwala-visiontree** [comment]
I figured it out! I had a mismatch between the requested scopes coming from the client, and the access policy. There were some scopes being requested which there was no matching access policy, but when I updated the access policy everything is now working! it is pretty cool stuff.
